services:
  # Servicio de PostgreSQL
  postgres:
    image: postgres:17-alpine
    container_name: gestlib-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gestlib-network

  # Servicio del backend NestJS
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gestlib-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DATABASE_HOST=postgres
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - gestlib-network

  # Servicio opcional de pgAdmin para administrar la base de datos
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gestlib-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - gestlib-network

volumes:
  postgres_data:

networks:
  gestlib-network:
    driver: bridge